name: Continuous Integration Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'dist/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

permissions:
  contents: write

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  build-in-x86-arch:
    needs: [test-javascript]
    name: Build Actions in x86 arch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build
        run: npm run bundle

      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build dist
          branch: main
